kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha1
metadata:
  name: web-terminal
  namespace: openshift-terminal
  annotations:
    controller.devfile.io/restricted-access: "true"
  labels:
    console.openshift.io/terminal: "true"
spec:
  started: true
  routingClass: 'web-terminal'
  template:
    components:
      - plugin:
          name: web-terminal
          id: redhat-developer/web-terminal/4.5.0
      - container:
          name: dev
          image: quay.io/rhosak/rhoas-web-terminal-tooling-rhel8
          memoryLimit: 256Mi
          args: ["tail", "-f", "/dev/null"]